name: first_workflow
on:
        push:
                branches: [ master ]

jobs: 
 job_one:
        name: Deploy
        runs-on: ubuntu-latest
        steps: 
                - name: testing auto deployment of code
                  uses: appleboy/ssh-action@master
                  with: 
                        host: ec2-52-4-172-217.compute-1.amazonaws.com.
                        username: ubuntu
                        key: ${{ secrets.TEST_WORKFLOW_SECRET}}
                        port: 22
                        script: |
                           whoami




