name: first_workflow
on:
        push:
                branches: [ master ]

jobs: 
 job_one:
        name: Deploy
        runs-on: ubuntu-latest
        steps: 
                - name: testing auto deployment of code
                  uses: appleboy/ssh-action@v0.1.4
                  with: 
                        host: 18.210.144.107
                        username: ubuntu
                        key: ${{ secrets.TEST_WORKFLOW_SECRET}}
                        port: 80
                        script: |
                           whoami




