name: first_workflow
on:
        push:
                branches: [ master ]

jobs: 
 job_one:
        name: Deploy
        runs-on: ubuntu-latest
        steps: 
                - name: testing auto deployment of code
                  uses: appleboy/ssh-action@master
                  with: 
                        host: 52.4.172.217
                        username: akashmahajan1994
                        key: ${{ secrets.TEST_WORKFLOW_SECRET}}
                        port: 80
                        script: |
                           whoami




